# k8s/helm/streamforge/Chart.yaml

apiVersion: v2
name: streamforge
description: A Helm chart for StreamForge Netflix-like OTT Platform
type: application
version: 0.1.0
appVersion: "1.0.0"

keywords:
  - netflix-clone
  - ott-platform
  - streaming
  - video
  - kubernetes
  - aws
  - eks

home: https://github.com/prajwalkhandare/streamforge
sources:
  - https://github.com/prajwalkhandare/streamforge

maintainers:
  - name: Prajwal Khandare
    email: prajwal.khandare@example.com
    url: https://linkedin.com/in/prajwal-khandare-18254b212

dependencies:
  - name: postgresql
    version: 12.x.x
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: redis
    version: 17.x.x
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled

    